# -*- coding: utf-8 -*-
"""Python_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek8DQ6usuhwc5swuwySip4N1yHKBIzoL
"""

print ("This is Python Assignment")

a=5
b=10
print("Addition of a+b is:",a+b)

a = int(input("Enter the First number: "))
b = int(input("Enter the Second number: "))

Addition = a+b
Substraction = a-b
Multiplication = a*b
Division = a/b


print("Addition of First and Second Number is :",Addition)
print("Substraction of First and Second Number is :",Substraction)
print("Multiplication of First and Second Number is :",Multiplication)
print("Division of First and Second Number is :",Division)

